import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Image src="/ecologo.svg" height={150} width={150} />
        <h1 className={styles.title}>
          Welcome to <a href="/">Ecolometrics!</a>
        </h1>

        <p className={styles.description}>Open knowledge hub on ecological transitions</p>
        <p className={styles.update}>⚡ Coming soon.</p>
      </main>

      <footer className={styles.footer}>
        <p>
          {" "}
          Powered by the <span className={styles.logo}>David Bros</span>
        </p>
      </footer>
    </div>
  );
}
